<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CBT-2F-301" ignored="0" name="Test" tests="3" failures="1" timestamp="2021-03-19T13:08:53 IST" time="41.971" errors="0">
  <testcase name="invalidLogin" time="6.942" classname="com_ActiTime_Test.InvalidLoginTest"/>
  <testcase name="validLoginLogout" time="4.941" classname="com_ActiTime_Test.ValidLoginLogoutTest"/>
  <testcase name="verifyVersion" time="0.124" classname="com_ActiTime_Test.VerifyversionTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [actiTIME 2020] but found [actiTIME 2020 Online]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [actiTIME 2020] but found [actiTIME 2020 Online]
at com_ActiTime_Test.VerifyversionTest.verifyVersion(VerifyversionTest.java:26)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verifyVersion -->
</testsuite> <!-- Test -->
